[package]
name = "oxat"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
futures = "0.3.31"
miette = "7.2.0"
ratatui = "0.29.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
smol = "2.0.2"
surf = "2.3.2"
